Feature: Top Bar Component
chingu-voyages/v8-geckos-team-13 pull request #4
Opened 2019-03-29 11:45 UTC by jamsgra

#### What does this PR do?
Displays the Top Bar component with logo, menu & search bar.

#### Description of Task to be completed?

Check that the component displays without errors.

#### How should this be manually tested?
`npm start`

2019-03-29 13:17 UTC, janselme approved these changes
Everything works as expected.
Quick question: what do you think about placing the input field first in the search component?
I didn't notice the input on the right of the button.

2019-03-29 15:32 UTC, abdulfatai360 requested changes
Hello @jamsgra  Well done for the nice work. I agree with @janselme about placing the search field first before the button.

I also want to suggest that instead of having the menu items stack vertically on small screen, try to make the menu collapsible on small screen and have them spread out on large as its commonly seen on websites these days.

That should be considered greatly as it's key to making the site truly responsive.

Thanks

2019-03-30 12:57 UTC, djordjijem reviewed
- When i click on the search icon i want the search field to get opened smoothly (u will have just the icon; when u click u get search filed, google the various examples)or to make them as one element without smoothing (the form) but be careful, forms are tricky. Hint: you need to disable its default behaviour in order to work properly. When you don't have idea how something should be coded i suggest you go on this [link](https://www.w3schools.com/howto/howto_css_icon_bar.asp)   to see how they did it (everybody does that, its fine)

-it's not responsive. Just google responsive layout and read the basics pls, and then see the proper solutions for ur component.Aggain i suggest the previous link

You are sure you wanna writte test for React components ? :P

-Design in general is very nice, i like the fonts and the colors. Guess thats Jennifers fault xD

2019-04-02 13:50 UTC, abdulfatai360 approved these changes

2019-04-02 14:04 UTC, merged