Ft article grid
chingu-voyages/v8-geckos-team-13 pull request #5
Opened 2019-04-02 17:02 UTC by djordjijem

Everything should be fine, except some little style details, which for i currently don't have time. @jamsgra  look at how little code i needed for 10x more work; if i did this with pure HTML CSS i would need whole day, maybe two to fix everything, thats why we have frameworks man xD I need also to fix the grid a little bit and to make that cool borders around the articles, will open an issue for that. 

Cheers!

2019-04-03 20:33 UTC, janselme requested changes
Hi,
Can we keep the App width to 100% instead of 80%, please?
FYI, I had an error in the console, saying: `Each child in a list should have a unique "key" prop.` 
Looking forward to some explanations 👍

2019-04-04 09:02 UTC, djordjijem commented
hi @janselme , i think i tested something and forgot to change back to 100%, ofc no probs. Don't worry about the errors in the console, it's not important without functionallity, but thanks on the follow up anyway. If you don't know what is it; React requires that every list has unique key so that every time it changes he knows what list exactly changed. We ll manage that latter, deal with errors in the console etc.

2019-04-04 19:13 UTC, janselme approved these changes

2019-04-11 12:30 UTC, jamsgra approved these changes

2019-04-11 12:30 UTC, merged